// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalFileDescription {
    #[prost(string, tag = "1")]
    pub local_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub file_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub hash_sha1: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListLocalFilesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListLocalFilesResponse {
    #[prost(message, repeated, tag = "1")]
    pub file_descs: ::prost::alloc::vec::Vec<LocalFileDescription>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileAddRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileAddResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileRemoveRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileRemoveResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileListRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileListResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListHostsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListHostsResponse {
    #[prost(message, repeated, tag = "1")]
    pub servers_info: ::prost::alloc::vec::Vec<super::shared::ServerInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DiscoverHostsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoverHostsResponse {
    #[prost(message, repeated, tag = "1")]
    pub servers_info: ::prost::alloc::vec::Vec<super::shared::ServerInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddFileRequest {
    #[prost(string, repeated, tag = "1")]
    pub file_path: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AddFileResponse {}
/// Generated client implementations.
pub mod client_api_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ClientApiClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ClientApiClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ClientApiClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ClientApiClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ClientApiClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn add_file(
            &mut self,
            request: impl tonic::IntoRequest<super::AddFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/cli.ClientApi/AddFile");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("cli.ClientApi", "AddFile"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_hosts(
            &mut self,
            request: impl tonic::IntoRequest<super::ListHostsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListHostsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/cli.ClientApi/ListHosts");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("cli.ClientApi", "ListHosts"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn discover_hosts(
            &mut self,
            request: impl tonic::IntoRequest<super::DiscoverHostsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DiscoverHostsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cli.ClientApi/DiscoverHosts",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cli.ClientApi", "DiscoverHosts"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_local_files(
            &mut self,
            request: impl tonic::IntoRequest<super::ListLocalFilesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListLocalFilesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cli.ClientApi/ListLocalFiles",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cli.ClientApi", "ListLocalFiles"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod client_api_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ClientApiServer.
    #[async_trait]
    pub trait ClientApi: std::marker::Send + std::marker::Sync + 'static {
        async fn add_file(
            &self,
            request: tonic::Request<super::AddFileRequest>,
        ) -> std::result::Result<tonic::Response<super::AddFileResponse>, tonic::Status>;
        async fn list_hosts(
            &self,
            request: tonic::Request<super::ListHostsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListHostsResponse>,
            tonic::Status,
        >;
        async fn discover_hosts(
            &self,
            request: tonic::Request<super::DiscoverHostsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DiscoverHostsResponse>,
            tonic::Status,
        >;
        async fn list_local_files(
            &self,
            request: tonic::Request<super::ListLocalFilesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListLocalFilesResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct ClientApiServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ClientApiServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ClientApiServer<T>
    where
        T: ClientApi,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cli.ClientApi/AddFile" => {
                    #[allow(non_camel_case_types)]
                    struct AddFileSvc<T: ClientApi>(pub Arc<T>);
                    impl<T: ClientApi> tonic::server::UnaryService<super::AddFileRequest>
                    for AddFileSvc<T> {
                        type Response = super::AddFileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ClientApi>::add_file(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddFileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cli.ClientApi/ListHosts" => {
                    #[allow(non_camel_case_types)]
                    struct ListHostsSvc<T: ClientApi>(pub Arc<T>);
                    impl<
                        T: ClientApi,
                    > tonic::server::UnaryService<super::ListHostsRequest>
                    for ListHostsSvc<T> {
                        type Response = super::ListHostsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListHostsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ClientApi>::list_hosts(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListHostsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cli.ClientApi/DiscoverHosts" => {
                    #[allow(non_camel_case_types)]
                    struct DiscoverHostsSvc<T: ClientApi>(pub Arc<T>);
                    impl<
                        T: ClientApi,
                    > tonic::server::UnaryService<super::DiscoverHostsRequest>
                    for DiscoverHostsSvc<T> {
                        type Response = super::DiscoverHostsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DiscoverHostsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ClientApi>::discover_hosts(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DiscoverHostsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cli.ClientApi/ListLocalFiles" => {
                    #[allow(non_camel_case_types)]
                    struct ListLocalFilesSvc<T: ClientApi>(pub Arc<T>);
                    impl<
                        T: ClientApi,
                    > tonic::server::UnaryService<super::ListLocalFilesRequest>
                    for ListLocalFilesSvc<T> {
                        type Response = super::ListLocalFilesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListLocalFilesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ClientApi>::list_local_files(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListLocalFilesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ClientApiServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cli.ClientApi";
    impl<T> tonic::server::NamedService for ClientApiServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
